// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LctqYWomqoaMR9FXDsJivtI05DA3qBc',
    appId: '1:715425486283:web:fa6c95a6bf89a44a38924e',
    messagingSenderId: '715425486283',
    projectId: 'krushnlila-food-delivery',
    authDomain: 'krushnlila-food-delivery.firebaseapp.com',
    storageBucket: 'krushnlila-food-delivery.firebasestorage.app',
    measurementId: 'G-DS5W7Y5X3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOZqQiW9qRFRByDfpFw3wUSe_hEQ8eWE',
    appId: '1:715425486283:android:29067d3728d0682038924e',
    messagingSenderId: '715425486283',
    projectId: 'krushnlila-food-delivery',
    storageBucket: 'krushnlila-food-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtKS7yh1Tavtxumzb-t_xMHZGrhO5KVI',
    appId: '1:715425486283:ios:fea23d40d8ee397138924e',
    messagingSenderId: '715425486283',
    projectId: 'krushnlila-food-delivery',
    storageBucket: 'krushnlila-food-delivery.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtKS7yh1Tavtxumzb-t_xMHZGrhO5KVI',
    appId: '1:715425486283:ios:fea23d40d8ee397138924e',
    messagingSenderId: '715425486283',
    projectId: 'krushnlila-food-delivery',
    storageBucket: 'krushnlila-food-delivery.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0LctqYWomqoaMR9FXDsJivtI05DA3qBc',
    appId: '1:715425486283:web:c27b17137af2258c38924e',
    messagingSenderId: '715425486283',
    projectId: 'krushnlila-food-delivery',
    authDomain: 'krushnlila-food-delivery.firebaseapp.com',
    storageBucket: 'krushnlila-food-delivery.firebasestorage.app',
    measurementId: 'G-FBPK49D1QB',
  );
}
